{% set name = "oneat-augmentations" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oneat_augmentations-{{ version }}.tar.gz
  sha256: d442a3de3093dc4a6ac3ddf5947111c789cfc23164f5faa63a9a07973782c2a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - albumentations
    - dask-core
    - natsort
    - opencv
    - pandas
    - photutils
    - python >=3.9
    - scikit-learn
    - scipy

test:
  imports:
    - oneat_augmentations
  commands:
    - pip list
    # - pip check  # Fails due to sklearn and opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/Augmentations/
  summary: |
    Augmentations for volume, planar segmentation, classification
    image segmentation and associated csv file of oneat clicks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
